config/routes.rb
Rss::Application.routes.draw do
  resources :filters

  resources :subscriptions

  resources :users

  root :controller => "subscriptions", :action => "index"

  
  match ':controller(/:action(/:id(.:format)))'
  match '/login', :controller => 'users', :action => 'login'
  match '/logout', :controller => 'users', :action => 'logout'
  match '/register', :controller => 'users', :action => 'new'
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  
  layout "template"
  
  require 'rss/1.0'
  require 'rss/2.0'
  require 'open-uri'
  
  # GET /subscriptions
  # GET /subscriptions.xml
  def index 
    if session[:user_id] 
      @subscriptions = Subscription.all(:conditions => ["user_id = ?", session[:user_id]])
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @subscriptions }
      end
    else
      redirect_to "/login"
    end
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.xml
  def show
    if session[:user_id] 
      @subscription = Subscription.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @subscription }
      end
    end
  end

  # GET /subscriptions/new
  # GET /subscriptions/new.xml
  def new
    if session[:user_id] 
      @subscription = Subscription.new
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @subscription }
      end
    end
  end

  # GET /subscriptions/1/edit
  def edit
    if session[:user_id] 
      @subscription = Subscription.find(params[:id])
    end
  end

  # POST /subscriptions
  # POST /subscriptions.xml
  def create
    if session[:user_id] 
      user = User.find(session[:user_id])
      s = Subscription.new
      s.url = params[:subscription][:url]
      s.title = params[:subscription][:title]
      s.user = user
      @subscription = s
  
      respond_to do |format|
        if @subscription.save
          format.html { redirect_to(@subscription, :notice => 'Subscription was successfully created.') }
          format.xml  { render :xml => @subscription, :status => :created, :location => @subscription }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @subscription.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /subscriptions/1
  # PUT /subscriptions/1.xml
  def update
    if session[:user_id] 
      @subscription = Subscription.find(params[:id])
  
      respond_to do |format|
        if @subscription.update_attributes(params[:subscription])
          format.html { redirect_to(@subscription, :notice => 'Subscription was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @subscription.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.xml
  def destroy
    if session[:user_id] 
      @subscription = Subscription.find(params[:id])
      @subscription.destroy
  
      respond_to do |format|
        format.html { redirect_to(subscriptions_url) }
        format.xml  { head :ok }
      end
    end
  end
  
  def read
    if session[:user_id] 
      
      @subscription = Subscription.find(params[:id], :conditions => ["user_id = ?", session[:user_id]])
      @filters = Filter.all(:conditions => ["subscription_id = ?", @subscription.id])
      
      @arrFilter = Array.new
      @filters.each do |f|
        @arrFilter.push f.name
      end  
      source = @subscription.url
      content = ""
      open(source) do |s| 
        content = s.read 
      end
      @rss = RSS::Parser.parse(content, false)
      @arrPosts = Array.new
      if @arrFilter.size > 0
  		  @rss.items.each do |item|
          @arrFilter.each do |filter|
    			  if item.description.include?(filter)
    				  @arrPosts.push [item.title, item.link, item.description]
    			  else
    				
    			  end
    			end
  		  end
  	  else
  	 	   @rss.items.each do |item|
    			 @arrPosts.push [item.title, item.link, item.description]
    		 end
	    end
	  
      @arrPosts.uniq!
      
      @link = Array.new
      @rss.items.each do |item|
        #logger.info item.description
      	if !@rss.channel.description.nil?
      	  s = @rss.channel.description.include?("reddit")
      	  if s 
      	    images = item.description.scan(/href=".*?"/i)
      	    images.each do |image|
      	      if image.include?("png") || image.include?("jpg") || image.include?("gif") 
            		image = image.gsub("href=", "")
            		image = image.gsub('"', "")
            		@link.push(Array.new([image, item.title]))
      	      end
      	    end
      	  end
      	end
      end
      
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @subscriptions }
      end
    end
  end
  
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>
<br />
<table>
<% @subscriptions.each do |subscription| %>
  <tr>
  	<td><%= subscription.title %></td>
	<td><%= link_to "Read", "/subscriptions/read/" + subscription.id.to_s  %></td>
    <td><%= link_to 'View', subscription %></td>
    <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
    <td><%= link_to 'Delete', subscription, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Add new subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/read.html.erb
<h1>Listing subscriptions</h1>
<br />
<%= @rss.channel.title %>
<br />

<% @link.each do |item| %>
	<div>
		<h3><%=item[1]%></h3>
	</div>
	<img src="<%= raw(item[0].to_s)%>" alt="" style="max-width: 760px" /> 
	<br /><br /><hr />
<% end %>

<% @arrPosts.each do |item| %>
	<div style="padding: 10px;">
		<%= link_to item[0], item[1] %>
	</div>
	<div style="padding: 10px;">
		<%= raw(item[2]) %>
	</div>
	<hr />
<% end %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @subscription.user.name %>
</p>

<p>
  <b>Title:</b>
  <%= @subscription.title %>
</p>

<p>
  <b>Url:</b>
  <%= @subscription.url %>
</p>


<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>