config/routes.rb
Rss::Application.routes.draw do
  resources :filters

  resources :subscriptions

  resources :users

  root :controller => "subscriptions", :action => "index"

  
  match ':controller(/:action(/:id(.:format)))'
  match '/login', :controller => 'users', :action => 'login'
  match '/logout', :controller => 'users', :action => 'logout'
  match '/register', :controller => 'users', :action => 'new'
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  belongs_to :filter
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  
  layout "template"
  
  # GET /filters
  # GET /filters.xml
  def index
    if session[:user_id]
      subs = Subscription.all(:conditions => ["user_id = ?", session[:user_id]])
      
      @filters = Array.new
      
      subs.each do |s|
        filter = Filter.all(:conditions => ["subscription_id = ?", s.id])
        filter.each do |f|
          @filters.push f
        end
      end
      
      #@filters = Filter.all
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @filters }
      end
    else
      redirect_to "/login"
    end
  end

  # GET /filters/1
  # GET /filters/1.xml
  def show
    if session[:user_id]
      @filter = Filter.find(params[:id])
      sub = Subscription.find(@filter.subscription_id)
      @s = sub.title
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @filter }
      end
    else
      redirect_to "/login"
    end
  end

  # GET /filters/new
  # GET /filters/new.xml
  def new
    if session[:user_id]
      @filter = Filter.new
      @subscriptions = Subscription.all(:conditions => ["user_id = ?", session[:user_id]])
      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @filter }
      end
    else
      redirect_to "/login"
    end
  end

  # GET /filters/1/edit
  def edit
    if session[:user_id]
      @filter = Filter.find(params[:id])
      @subscriptions = Subscription.all(:conditions => ["user_id = ?", session[:user_id]])
    else
      redirect_to "/login"
    end
  end

  # POST /filters
  # POST /filters.xml
  def create
    if session[:user_id]
      sub = Subscription.find(params[:filter][:subscription_id])
      
      @filter = Filter.new
      @filter.name = params[:filter][:name]
      @filter.subscription_id = sub.id
      
      respond_to do |format|
        if @filter.save
          format.html { redirect_to(@filter, :notice => 'Filter was successfully created.') }
          format.xml  { render :xml => @filter, :status => :created, :location => @filter }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @filter.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to "/login"
    end
  end

  # PUT /filters/1
  # PUT /filters/1.xml
  def update
    if session[:user_id]
      @filter = Filter.find(params[:id])
  
      respond_to do |format|
        if @filter.update_attributes(params[:filter])
          format.html { redirect_to(@filter, :notice => 'Filter was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @filter.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to "/login"
    end
  end

  # DELETE /filters/1
  # DELETE /filters/1.xml
  def destroy
    if session[:user_id]
      @filter = Filter.find(params[:id])
      @filter.destroy
  
      respond_to do |format|
        format.html { redirect_to(filters_url) }
        format.xml  { head :ok }
      end
    else
      redirect_to "/login"
    end
  end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_form.html.erb
<%= form_for(@filter) do |f| %>
  <% if @filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
      <% @filter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />
  <div class="field">
  	<%= f.label "Subscription" %><br />
	<%= f.select(:subscription_id, @subscriptions.map {|sub| [sub.title, sub.id]}) %>
  </div>
  <div class="field">
    <%= f.label "Filter" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filters/edit.html.erb
<h1>Editing filter</h1>

<%= render 'form' %>

<%= link_to 'Show', @filter %> |
<%= link_to 'Back', filters_path %>

app/views/filters/index.html.erb
<h1>Listing filters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Subscription</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @filters.each do |filter| %>
  <tr>
    <td><%= filter.name %></td>
    <td><%= Subscription.find(filter.subscription_id).title %></td>
    <td><%= link_to 'Show', filter %></td>
    <td><%= link_to 'Edit', edit_filter_path(filter) %></td>
    <td><%= link_to 'Delete', filter, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add new filter', new_filter_path %>

app/views/filters/new.html.erb
<h1>New filter</h1>

<%= render 'form' %>

<%= link_to 'Back', filters_path %>

app/views/filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subscription:</b>
  <%= @s %>
</p>
<p>
  <b>Name:</b>
  <%= @filter.name %>
</p>

<br />

<%= link_to 'Edit', edit_filter_path(@filter) %> |
<%= link_to 'Back', filters_path %>